$.post('/api/config/admin', {
    "oae-authentication/local/allowAccountCreation": "true",
    "oae-authentication/twitter/enabled": "false",
    "oae-content/visibility/files": "private",
    "oae-content/visibility/folders": "private",
    "oae-content/visibility/links": "private",
    "oae-discussions/visibility/discussion": "private",
    "oae-email/general/fromAddress": "",
    "oae-email/general/fromName": "*Unity",
    "oae-principals/group/visibility": "private",
    "oae-principals/termsAndConditions/enabled": "true",
    "oae-principals/user/emailPreference": "immediate",
    "oae-tenants/block_2/lg": "4",
    "oae-tenants/block_2/md": "4",
    "oae-tenants/block_2/minHeight": "",
    "oae-tenants/block_2/text/default": "# \\*Unity\n\nThe cloud where universities work together",
    "oae-tenants/block_2/textColor": "#BD1C19",
    "oae-tenants/block_2/titleColor": "#333333",
    "oae-tenants/block_2/type": "text",
    "oae-tenants/block_2/videoPlaceholder": "",
    "oae-tenants/block_2/videoUrl": "",
    "oae-tenants/block_3/imgUrl": "/assets/landingpage/video.png",
    "oae-tenants/block_3/lg": "8",
    "oae-tenants/block_3/md": "8",
    "oae-tenants/block_3/sm": "12",
    "oae-tenants/block_3/text/default": "# __MSG__SUPPORTING_ACADEMIC_COLLABORATION__\n __MSG__A_POWERFULL_NEW_WAY_FOR_STUDENTS_AND_FACULTY_TO_CREATE_KNOWLEDGE_COLLABORATE_AND_CONNECT_WITH_THE_WORLD__",
    "oae-tenants/block_3/textColor": "",
    "oae-tenants/block_3/titleColor": "",
    "oae-tenants/block_3/type": "image",
    "oae-tenants/block_4/bgColor": "#222222",
    "oae-tenants/block_4/icon": "fa-comments",
    "oae-tenants/block_4/text/default": "#### Introducing \\*Unity\n\n\\*Unity is a new cloud collaboration service that makes it easy for academics to work together.",
    "oae-tenants/block_4/textColor": "#D8D8D8",
    "oae-tenants/block_4/titleColor": "#D8D8D8",
    "oae-tenants/block_5/bgColor": "#E9E8E4",
    "oae-tenants/block_5/icon": "fa-group",
    "oae-tenants/block_5/lg": "8",
    "oae-tenants/block_5/md": "8",
    "oae-tenants/block_5/sm": "12",
    "oae-tenants/block_5/text/default": "#### Built by universities, for universities\n\n You can share files, chat and collaborate in real time. With people in your own university. Or thousands of others.",
    "oae-tenants/block_5/textColor": "#333",
    "oae-tenants/block_5/titleColor": "#333",
    "oae-tenants/block_6/bgColor": "",
    "oae-tenants/block_6/icon": "",
    "oae-tenants/block_6/lg": "12",
    "oae-tenants/block_6/md": "12",
    "oae-tenants/block_6/sm": "12",
    "oae-tenants/block_6/text/default": "Note that \\*Unity is not an official campus service. Find out more about \\*Unity at [http://www.unity.ac](http://www.unity.ac).",
    "oae-tenants/block_6/textColor": "#333",
    "oae-tenants/block_6/titleColor": "#333",
    "oae-tenants/block_6/type": "text",
    "oae-tenants/instance/hostingOrganization": "*Research",
    "oae-tenants/instance/hostingOrganizationURL": "http://www.researchresearch.com",
    "oae-tenants/instance/instanceName": "*Unity",
    "oae-tenants/instance/instanceURL": "http://unity.ac",
    "oae-ui/skin/variables": "{\"institutional-logo-url\":\"'/assets/default/large.png'\",\"branding-image-url\":\"'/assets/landingpage/branding.png'\",\"branding-gradient1-color\":\"rgba(255, 255, 255, 0.34)\",\"branding-gradient2-color\":\"rgba(255, 255, 255, 0.34)\"}"
});
